name: local project

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch: # allows you to trigger manually

defaults:
  run:
    shell: bash -l {0}

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: local-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.variant }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest # x86-64
          - ubuntu-24.04-arm # ARM
          - macos-15-intel # x86-64
          - macos-latest # ARM
        variant:
          - default
          - asan
          - tsan

    steps:
      - name: Checkout hdf5-pixi and hdf5
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.62.0
          environments: build

      - name: List conda packages
        run: pixi ls -e build

      - name: List files in conda environment
        run: pixi run -e build conda-list

      - name: set CFLAGS for ASAN
        if: matrix.variant == 'asan'
        run: |
          echo "CFLAGS='-fsanitize=address'" >> $GITHUB_ENV
          echo "LDFLAGS='-fsanitize=address'" >> $GITHUB_ENV

      - name: set CFLAGS for TSAN
        if: matrix.variant == 'tsan'
        run: |
          echo "CFLAGS='-fsanitize=thread'" >> $GITHUB_ENV
          echo "LDFLAGS='-fsanitize=thread'" >> $GITHUB_ENV

      - name: cmake
        env:
          CFLAGS: ${{ env.CFLAGS }}
        run: pixi run cmake

      - name: smoke test
        run: pixi run -e build smoke-test

      - name: ctest
        if: matrix.variant != 'tsan'  # FIXME many upstream test failures
        env:
          CFLAGS: ${{ env.CFLAGS }}
        run: pixi run ctest

      - name: cpack
        run: pixi run cpack

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: hdf5-pixi-${{ matrix.os }}-${{ matrix.variant }}
          path: build/HDF5-*
